url_name = fetch_url_name_by_id(id)

try:
    response = requests.get(url_name)
    response.raise_for_status()
except requests.HTTPError:
    flash('Произошла ошибка при проверке', 'danger')
    # возможно, другая обработка ошибки или return
else:
    status_code = response.status_code
    h1_content, title_text, description_content = parse_html(response.content)

    data = {
        "id": id,
        "status_code": status_code,
        "h1_content": h1_content,
        "title_text": title_text,
        "description_content": description_content
    }

    perform_url_check(data)
    flash('Страница успешно проверена', 'success')